//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TrackingCam.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "14.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("FoscamHD")]
        public string Camera_Type {
            get {
                return ((string)(this["Camera_Type"]));
            }
            set {
                this["Camera_Type"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://192.168.241.14:88")]
        public string Camera_Url {
            get {
                return ((string)(this["Camera_Url"]));
            }
            set {
                this["Camera_Url"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("admin1")]
        public string Camera_Username {
            get {
                return ((string)(this["Camera_Username"]));
            }
            set {
                this["Camera_Username"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("admin1")]
        public string Camera_Password {
            get {
                return ((string)(this["Camera_Password"]));
            }
            set {
                this["Camera_Password"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double Tracking_Distance {
            get {
                return ((double)(this["Tracking_Distance"]));
            }
            set {
                this["Tracking_Distance"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Tag1")]
        public string Tracking_ObjectKey {
            get {
                return ((string)(this["Tracking_ObjectKey"]));
            }
            set {
                this["Tracking_ObjectKey"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("10")]
        public double Pan_Angle_Step {
            get {
                return ((double)(this["Pan_Angle_Step"]));
            }
            set {
                this["Pan_Angle_Step"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("90")]
        public double Tilt_Angle_Step {
            get {
                return ((double)(this["Tilt_Angle_Step"]));
            }
            set {
                this["Tilt_Angle_Step"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("3.39863228797913")]
        public double Tracking_CameraX {
            get {
                return ((double)(this["Tracking_Camera_X"]));
            }
            set {
                this["Tracking_Camera_X"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("6.21996164321899")]
        public double Tracking_CameraY {
            get {
                return ((double)(this["Tracking_Camera_Y"]));
            }
            set {
                this["Tracking_Camera_Y"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("-0.881328535079954")]
        public double Tracking_CameraZ {
            get {
                return ((double)(this["Tracking_Camera_Z"]));
            }
            set {
                this["Tracking_Camera_Z"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Preset")]
        public string PTZ_PresetPrefix {
            get {
                return ((string)(this["PTZ_PresetPrefix"]));
            }
            set {
                this["PTZ_PresetPrefix"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("10")]
        public string PTZ_PresetCount {
            get {
                return ((string)(this["PTZ_PresetCount"]));
            }
            set {
                this["PTZ_PresetCount"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1.27")]
        public double Tracking_Min_X {
            get {
                return ((double)(this["Tracking_Min_X"]));
            }
            set {
                this["Tracking_Min_X"] = value;
            }
        }
    }
}
