//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TrackingCam.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "14.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("FoscamHD")]
        public string Camera_Type {
            get {
                return ((string)(this["Camera_Type"]));
            }
            set {
                this["Camera_Type"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://192.168.241.14:88")]
        public string Camera_Url {
            get {
                return ((string)(this["Camera_Url"]));
            }
            set {
                this["Camera_Url"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("admin1")]
        public string Camera_Username {
            get {
                return ((string)(this["Camera_Username"]));
            }
            set {
                this["Camera_Username"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("admin1")]
        public string Camera_Password {
            get {
                return ((string)(this["Camera_Password"]));
            }
            set {
                this["Camera_Password"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double Tracking_Distance {
            get {
                return ((double)(this["Tracking_Distance"]));
            }
            set {
                this["Tracking_Distance"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Tag1")]
        public string Tracking_ObjectKey {
            get {
                return ((string)(this["Tracking_ObjectKey"]));
            }
            set {
                this["Tracking_ObjectKey"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("3.23816204071045")]
        public double Tracking_CameraX {
            get {
                return ((double)(this["Tracking_CameraX"]));
            }
            set {
                this["Tracking_CameraX"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Preset")]
        public string PTZ_PresetPrefix {
            get {
                return ((string)(this["PTZ_PresetPrefix"]));
            }
            set {
                this["PTZ_PresetPrefix"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("10")]
        public int PTZ_PresetCount {
            get {
                return ((int)(this["PTZ_PresetCount"]));
            }
            set {
                this["PTZ_PresetCount"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("-45")]
        public double PTZ_MinPanAngle {
            get {
                return ((double)(this["PTZ_MinPanAngle"]));
            }
            set {
                this["PTZ_MinPanAngle"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("45")]
        public double PTZ_MaxPanAngle {
            get {
                return ((double)(this["PTZ_MaxPanAngle"]));
            }
            set {
                this["PTZ_MaxPanAngle"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("6.20297193527222")]
        public double Tracking_CameraY {
            get {
                return ((double)(this["Tracking_CameraY"]));
            }
            set {
                this["Tracking_CameraY"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("-0.714946579840356")]
        public double Tracking_CameraZ {
            get {
                return ((double)(this["Tracking_CameraZ"]));
            }
            set {
                this["Tracking_CameraZ"] = value;
            }
        }
    }
}
